### ISSUE TITLE
Create bootstrap script

### ISSUE THREAD

**Issue by mistycheney** [mistycheney/BrainSaliencyDetection#2]
> I was thinking about the issue of how to easily distribute the software.

> I think a good way would be to follow the standard convention where, after your clone the github directory, you go to the root directory and run "python setup.py install" which defines the different data directories and also sets environment variables that point to where the data is on gordon etc.

> Then there should be scripts for uploading to gordon, setting the parameters for the gabor filters etc, downloading results and then opening these results in the GUI.

**Comment by yoavfreund** [comment]
Hi Yuncong,

How are things going? Have you made progress with finding the significant
regions or with trying ICA?

Please update your wiki diary, you can point from there to any other web
page.

Are you available to meet today at 3:15 ?

Yoav

Prof. Yoav Freund
EBU3B, Room 4126
Dept. of Comp. Sci. & Eng.
http://www.cse.ucsd.edu/~yfreund/
Tel: (858)  534-1668
Email: yfreund@ucsd.edu
Calendar: http://tinyurl.com/n43h2f2
